/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ACER
 */
public class A_SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public A_SplashScreen() {
        initComponents();
        
         BgSs.setIcon(new FlatSVGIcon("Resource_SP/SplashScreen.svg", 1000, 563));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        persen = new javax.swing.JLabel();
        loading = new javax.swing.JProgressBar();
        load = new javax.swing.JLabel();
        BgSs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        persen.setBackground(new java.awt.Color(255, 255, 255));
        persen.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        persen.setForeground(new java.awt.Color(17, 137, 163));
        persen.setText("0%");
        getContentPane().add(persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 422, 40, 20));

        loading.setBackground(new java.awt.Color(255, 255, 255));
        loading.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        loading.setForeground(new java.awt.Color(17, 137, 163));
        getContentPane().add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 530, 10));

        load.setBackground(new java.awt.Color(17, 137, 163));
        load.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        load.setForeground(new java.awt.Color(17, 137, 163));
        load.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        load.setText("Loading");
        getContentPane().add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 240, -1));

        BgSs.setIcon(new FlatSVGIcon("resource/SplashScreen.svg"));
        BgSs.setText("BgSplashScreen");
        getContentPane().add(BgSs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        // Atur tema FlatLaf sebelum JFrame dibuat
        try {
            UIManager.setLookAndFeel(new FlatLightLaf()); // Pilih tema FlatLightLaf
        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize FlatLaf: " + ex.getMessage());
        }

        // Jalankan splash screen
        A_SplashScreen sp = new A_SplashScreen();
        sp.setVisible(true);

        B_Login lg = new B_Login();

        try {
            for (int i = 0; i <= 100; i++) { // Ubah kondisi menjadi <= agar progres mencapai 100%
                Thread.sleep(80); // Simulasi waktu loading
                
                sp.persen.setText(i + "%");
                sp.loading.setValue(i); // Update nilai progress bar
                
                // Ubah teks sesuai tahap progres
                if (i == 10) sp.load.setText("Loading database...");
                if (i == 40) sp.load.setText("Loading gambar...");
                if (i == 60) sp.load.setText("Loading menu...");
                if (i == 70) sp.load.setText("Loading komponen...");
                if (i == 80) sp.load.setText("Membuka aplikasi...");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(sp, e);
        }

        sp.dispose(); // Hilangkan A_SplashScreen
        lg.setVisible(true); // Tampilkan A_Login
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgSs;
    private javax.swing.JLabel load;
    private javax.swing.JProgressBar loading;
    private javax.swing.JLabel persen;
    // End of variables declaration//GEN-END:variables
}
