/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel_AP;

import Main.B_Login;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import Panel_Setting.SET_AboutApp;
import Panel_Setting.SET_AboutUs;
import Panel_Setting.SET_Ref;
import com.formdev.flatlaf.extras.FlatSVGIcon;

public class AP_Setting extends javax.swing.JPanel {

    // JLabel aktif
    private JLabel activeLabel;

    public AP_Setting() {
        initComponents();
        
        bt_abtapp.setIcon(new FlatSVGIcon("Resource_Setting/icon-aboutapp.svg", 23, 23));
        bt_abtus.setIcon(new FlatSVGIcon("Resource_Setting/icon-aboutus.svg", 23, 23));
        bt_ref.setIcon(new FlatSVGIcon("Resource_Setting/icon-reference.svg", 23, 23));
        btn_out.setIcon(new FlatSVGIcon("Resource_Setting/icon-out.svg", 30, 30));
        
        

        // Menambahkan panel ke pnl_utama
        pnl_utama.add("AboutApp", new SET_AboutApp());
        pnl_utama.add("AboutUs", new SET_AboutUs());
        pnl_utama.add("Reference", new SET_Ref());

        // Set default panel
        switchPanel("AboutApp");
        setActiveLabel(bt_abtapp);
    }

    private void switchPanel(String panelName) {
        // Pindahkan panel menggunakan CardLayout
        CardLayout cardLayout = (CardLayout) pnl_utama.getLayout();
        cardLayout.show(pnl_utama, panelName);
    }

    private void setActiveLabel(JLabel label) {
        if (activeLabel != null) {
            // Reset garis putih dari label sebelumnya
            activeLabel.setBorder(null);
        }
        // Set garis putih di bawah label yang baru
        label.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));
        activeLabel = label;
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_bar = new Costum.PanelRound();
        txt_pengaturan = new javax.swing.JLabel();
        bt_abtapp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt_abtus = new javax.swing.JLabel();
        bt_ref = new javax.swing.JLabel();
        btn_out = new javax.swing.JLabel();
        pnl_utama1 = new Costum.PanelRound();
        pnl_utama = new Costum.PanelRound();

        setBackground(new java.awt.Color(239, 242, 251));

        pnl_bar.setBackground(new java.awt.Color(17, 137, 163));
        pnl_bar.setRoundBottomLeft(50);
        pnl_bar.setRoundBottomRight(50);
        pnl_bar.setRoundTopLeft(50);
        pnl_bar.setRoundTopRight(50);

        txt_pengaturan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txt_pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        txt_pengaturan.setText("Pengaturan");

        bt_abtapp.setFont(new java.awt.Font("Futura Bk BT", 1, 14)); // NOI18N
        bt_abtapp.setForeground(new java.awt.Color(255, 255, 255));
        bt_abtapp.setText("About App");
        bt_abtapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_abtappMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_abtappMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_abtappMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 4));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        bt_abtus.setFont(new java.awt.Font("Futura Bk BT", 1, 14)); // NOI18N
        bt_abtus.setForeground(new java.awt.Color(255, 255, 255));
        bt_abtus.setText("About Us");
        bt_abtus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_abtusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_abtusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_abtusMouseExited(evt);
            }
        });

        bt_ref.setFont(new java.awt.Font("Futura Bk BT", 1, 14)); // NOI18N
        bt_ref.setForeground(new java.awt.Color(255, 255, 255));
        bt_ref.setText("Reference");
        bt_ref.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_refMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_refMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_refMouseExited(evt);
            }
        });

        btn_out.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        btn_out.setForeground(new java.awt.Color(255, 255, 255));
        btn_out.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_out.setText("Keluar");
        btn_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_outMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_outMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_outMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_outMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_outMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnl_barLayout = new javax.swing.GroupLayout(pnl_bar);
        pnl_bar.setLayout(pnl_barLayout);
        pnl_barLayout.setHorizontalGroup(
            pnl_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnl_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_abtapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_abtus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(pnl_barLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txt_pengaturan)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnl_barLayout.setVerticalGroup(
            pnl_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txt_pengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_abtapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bt_abtus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bt_ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(174, 174, 174)
                .addComponent(btn_out, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pnl_utama1.setBackground(new java.awt.Color(255, 255, 255));
        pnl_utama1.setRoundBottomLeft(50);
        pnl_utama1.setRoundBottomRight(50);
        pnl_utama1.setRoundTopLeft(50);
        pnl_utama1.setRoundTopRight(50);

        pnl_utama.setBackground(new java.awt.Color(255, 255, 255));
        pnl_utama.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnl_utama1Layout = new javax.swing.GroupLayout(pnl_utama1);
        pnl_utama1.setLayout(pnl_utama1Layout);
        pnl_utama1Layout.setHorizontalGroup(
            pnl_utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnl_utama1Layout.setVerticalGroup(
            pnl_utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_utama1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnl_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(pnl_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(pnl_utama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_utama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_abtappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abtappMouseClicked
        // TODO add your handling code here:
         switchPanel("AboutApp");
            setActiveLabel(bt_abtapp);
    }//GEN-LAST:event_bt_abtappMouseClicked

    private void bt_abtusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abtusMouseClicked
        // TODO add your handling code here:
         switchPanel("AboutUs");
                setActiveLabel(bt_abtus);
              
                
    }//GEN-LAST:event_bt_abtusMouseClicked

    private void bt_refMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_refMouseClicked
        // TODO add your handling code here:
         switchPanel("Reference");
                setActiveLabel(bt_ref);
               
    }//GEN-LAST:event_bt_refMouseClicked

    private void bt_abtappMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abtappMouseEntered
        // TODO add your handling code here:
        bt_abtapp.setOpaque(true);
        bt_abtapp.setBackground(new java.awt.Color(85, 157, 173));
        
    }//GEN-LAST:event_bt_abtappMouseEntered

    private void bt_abtappMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abtappMouseExited
        // TODO add your handling code here:
        bt_abtapp.setOpaque(false);
        bt_abtapp.setBackground(null);
    }//GEN-LAST:event_bt_abtappMouseExited

    private void bt_abtusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abtusMouseEntered
        // TODO add your handling code here:
        bt_abtus.setOpaque(true);
        bt_abtus.setBackground(new java.awt.Color(85, 157, 173));
    }//GEN-LAST:event_bt_abtusMouseEntered

    private void bt_abtusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abtusMouseExited
        // TODO add your handling code here:
        bt_abtus.setOpaque(false);
        bt_abtus.setBackground(null);
    }//GEN-LAST:event_bt_abtusMouseExited

    private void bt_refMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_refMouseEntered
        // TODO add your handling code here:
        bt_ref.setOpaque(true);
        bt_ref.setBackground(new java.awt.Color(85, 157, 173));
    }//GEN-LAST:event_bt_refMouseEntered

    private void bt_refMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_refMouseExited
        // TODO add your handling code here:
        bt_ref.setOpaque(false);
        bt_ref.setBackground(null);
    }//GEN-LAST:event_bt_refMouseExited

    private void btn_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_outMouseClicked
        // TODO add your handling code here:
      int pilihan = JOptionPane.showConfirmDialog(
            this, 
            "Apakah Anda ingin keluar?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE
        );

        if (pilihan == JOptionPane.YES_OPTION) {
            Window window = SwingUtilities.windowForComponent(this);
            if (window != null) {
                window.dispose(); // Menutup window yang sedang aktif
            }
            B_Login loginFrame = new B_Login();
            loginFrame.setVisible(true); // Menampilkan halaman login
        }
    }//GEN-LAST:event_btn_outMouseClicked

    private void btn_outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_outMouseEntered
        // TODO add your handling code here:
        btn_out.setOpaque(true);
        btn_out.setBackground(new java.awt.Color(167, 202, 209));
        btn_out.setForeground(new java.awt.Color(196, 42, 21));
    }//GEN-LAST:event_btn_outMouseEntered

    private void btn_outMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_outMouseExited
        // TODO add your handling code here:
        btn_out.setOpaque(false);
        btn_out.setBackground(null);
        btn_out.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btn_outMouseExited

    private void btn_outMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_outMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_outMousePressed

    private void btn_outMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_outMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_outMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_abtapp;
    private javax.swing.JLabel bt_abtus;
    private javax.swing.JLabel bt_ref;
    private javax.swing.JLabel btn_out;
    private javax.swing.JPanel jPanel1;
    private Costum.PanelRound pnl_bar;
    private Costum.PanelRound pnl_utama;
    private Costum.PanelRound pnl_utama1;
    private javax.swing.JLabel txt_pengaturan;
    // End of variables declaration//GEN-END:variables
}
